### ISSUE TITLE
Padding between fontIcon and text

### ISSUE THREAD

**Issue by druidamix** [medyo/fancybuttons#10]
Can you add a parameter to adjust manually the padding between fonticon and text and icon and text?

Now if the text is large enough, the icon grows in height instead of shrinking the padding between icon and text.

Thanks.

**Comment by medyo** [comment]
I'm sorry but i'm so busy right now, your request is not hard to add, you can implement in in like 5 to 10 minutes. Once made, just make a pull request so we can spread it to others.

**Comment by medyo** [comment]
You're so lucky, the internet goes off yesterday and so i decided to implement that feature.
check the version 1.1

**Comment by druidamix** [comment]
Is it uploaded to maven or jcenter? Android studio doesnt' resolve.

And. Thanks for your effort :+1:

**Comment by medyo** [comment]
It should be available in a few moments, it's syncing under Maven. Just wait

**Comment by medyo** [comment]
It's available now ! Happy Coding

**Comment by druidamix** [comment]
Thanks man :)

**Comment by druidamix** [comment]
Hi,

Still not avaliable to download from maven?

Something wrong uploading it?

**Comment by medyo** [comment]
Retry now, it works fine for me
