### ISSUE TITLE
`Clickable` attribute doesn't work

### ISSUE THREAD

**Issue by F0RIS** [medyo/Fancybuttons#100]
When I set  `android:clickable` and `android:focusable` attributes to `false` it doesn't work how it works in standart button. It must pass click event to parent view and not prevent it from further processing.
This can be usefull when necessary to set up one clicklistener at whole item like this one:
![image](https://user-images.githubusercontent.com/10178982/30873948-8ffb5906-a2f7-11e7-8233-6f6caf4fddbc.png)

Of course I can set all this in my code, but any way, it should copy this behavior from native android button

**Comment by MahdiPishguy** [comment]
@F0RIS could you paste your xml layout here to check that?

**Comment by F0RIS** [comment]
@MahdiPishguy https://pastebin.com/HfnvSH5h

**Comment by MahdiPishguy** [comment]
@F0RIS Thanks, in your layout parent xml as Linearlayout i see this attributes:

```
   android:clickable="false"
   android:focusable="false"
   android:focusableInTouchMode="false"
```

did you try to change them and test again?

**Comment by F0RIS** [comment]
@MahdiPishguy yes, FancyButton doesn't read clickable attribute from xml, it just set it here
https://github.com/medyo/Fancybuttons/blob/master/fancybuttons_library/src/main/java/mehdi/sakout/fancybuttons/FancyButton.java#L509

**Comment by MahdiPishguy** [comment]
@F0RIS yes you right, set that by default that cause of this problem, please let me to commenting them, thanks in advance

**Comment by MahdiPishguy** [comment]
@F0RIS did you try to commenting them on source code and use that on your project? instead of using gradle to install?

**Comment by F0RIS** [comment]
@MahdiPishguy Checked it now, with commenting next lines

`this.setClickable(true);
this.setFocusable(true);`

It works as it should

**Comment by MahdiPishguy** [comment]
@F0RIS ok, thanks, i commented them
