### ISSUE TITLE
remove icon programmatically

### ISSUE THREAD

**Issue by IgordeOliveira** [medyo/Fancybuttons#106]
it's possible? I'm trying to do this:                    
`btn_prox.setIconResource("");
`

**Comment by MahdiPishguy** [comment]
please wait to check that

**Comment by ayham95** [comment]
still waiting..

**Comment by medyo** [comment]
Hi @ayham95,

If you'd like to define a button without an icon, just ignore setting that field.
If you set `setIconResource("")` this could work but it's not recommended
