### ISSUE TITLE
Source code formatting

### ISSUE THREAD

**Issue by esafirm** [medyo/Fancybuttons#108]
Can the formatting in the source code using the default Android formatting style? 
I think since there's not many file we can change it easily. 

If not, can you please share the formatting configuration to make contribution easier. 

Thanks!

**Comment by medyo** [comment]
Hi @esafirm,

Could you handle this part and reformat the code ?

**Comment by MahdiPishguy** [comment]
this is not as issue, and we dont get any response from who created the issue
