### ISSUE TITLE
Black buttons that only show text "Fancy Buttons"

### ISSUE THREAD

**Issue by mikeslinkman** [medyo/Fancybuttons#117]
When I add and design a fancy button in my layout file the result that is outputted seems correct. Like the image [in this link](https://pasteboard.co/Hx0fKDE.png). However when I build the app to my phone the exact same button looks like the image shown [in this link](https://pasteboard.co/Hx0gPnI.jpg)

The button displayed here looks like the following in XML:
```

    <mehdi.sakout.fancybuttons.FancyButton
        android:id="@+id/btn_login"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@+id/end_middle_button"
        app:layout_constraintEnd_toStartOf="@+id/end_button_width"
        app:layout_constraintStart_toStartOf="@+id/start_button_width"
        app:layout_constraintTop_toTopOf="@+id/start_middle_button"
        fancy:fb_borderColor="#FFFFFF"
        fancy:fb_borderWidth="1dp"
        fancy:fb_defaultColor="#FFFFFF"
        fancy:fb_focusColor="#EEF2F5"
        fancy:fb_radius="30dp"
        fancy:fb_text="LOGIN"
        fancy:fb_textColor="#000000"
        fancy:fb_textSize="18sp">
    </mehdi.sakout.fancybuttons.FancyButton>
```

**Comment by MahdiPishguy** [comment]
@mikeslinkman whats your version of android you are test on that?

**Comment by Hanzyusuf** [comment]
same problem, i am using it in 'SwipeRevealLayout'
black button with white text 'Fancy Button'
android marshmellow

**Comment by MahdiPishguy** [comment]
@mikeslinkman @Hanzyusuf 

this version of android is new and we don't test and change core of this library on this version. please wait to release new new version

**Comment by DeveloperHu** [comment]
@Hanzyusuf same problem,but  have you add this?
`xmlns:fancy="http://schemas.android.com/apk/res-auto"`
not the 
` xmlns:fancy="http://schemas.android.com/tools"`
