### ISSUE TITLE
how i can set fb_fontIconResource

### ISSUE THREAD

**Issue by Abdelsattar** [medyo/Fancybuttons#119]
how ican set fb_fontIconResource with a resource ? and why it is not accpet drawable ?

**Comment by Abdelsattar** [comment]
so how to set right or left drawable ?

**Comment by medyo** [comment]
Hi @Abdelsattar,

You can do it programmatically, by calling `myButton.setIconResource(drawable)`

**Comment by Abdelsattar** [comment]
@medyo  yeah i found that after a while but why not in the xml the same ? of how to make it from xml

**Comment by medyo** [comment]
It's also doable, please refer to the samples: https://github.com/medyo/Fancybuttons/blob/master/samples/src/main/res/layout/activity_xml_buttons.xml
