### ISSUE TITLE
Hollow buttons focus color 

### ISSUE THREAD

**Issue by kadyEG** [medyo/fancybuttons#15]
If I have a hollow button ( With transparent background and a border ) ... the focus color colors the whole body , it could be tweaked to change the border only

**Comment by medyo** [comment]
It's more an enhancement than a bug, Maybe i can add it in the upcoming version. 
However if you really need it, it'll take you max 10 mins to implement it. Check that commit : 11c329030a9fd6bd65b117c348790c2b4524fefd by @sgultekin  to know how to add a new attribute.

**Comment by kadyEG** [comment]
Yes I am just simulating it with `onTouchListener` for now , I will go on with it , good luck ;)

**Comment by medyo** [comment]
Okay Abdelrahman, Have a good coding day :wink:
