### ISSUE TITLE
Setting text color programmatically doesn't change icon color

### ISSUE THREAD

**Issue by kadyEG** [medyo/fancybuttons#16]
using `setTextColor` changes only the text color without the icon's color , however setting it in the xml changes both

steps to reproduce : 

1. create a button in xml with a font icon
2. find and grab the button in an activity
3. call `setTextColor(int color)` on the button

The button will change only the text color and the icon color will remain as given in the xml

**Comment by medyo** [comment]
I think with your new pushed code, it's partially fixed

**Comment by kadyEG** [comment]
yes this should be closed as it's fixed on master :+1:
