### ISSUE TITLE
Attribute borderWidth has already been defined

### ISSUE THREAD

**Issue by sandeepwww** [medyo/fancybuttons#23]
I get this error when i try to sync the library with gradle. How to fix this

**Comment by medyo** [comment]
Thanks for noticing the conflict, it's caused due to presence of many attributes with same name, maybe another library is in conflict. i'll try to add a unique namespace for all fancybutton attributes.
it should be released in the coming version. (coming soon)

**Comment by medyo** [comment]
if you're pressed, you can use this branch https://github.com/medyo/fancybuttons/commit/9d9bab93a51bc3853c1b9626dd7a22a618b52b69 while awaiting deployment on maven

**Comment by squeeish** [comment]
Is it up in maven yet? I can't wait to try this library out.

**Comment by medyo** [comment]
sure, i'll deploy it as soon as possible.

**Comment by medyo** [comment]
It's live now, check the version 1.3

**Comment by squeeish** [comment]
@medyo excellent, I'm using it now. Thanks for this, makes buttons so much easier than having to deal with multiple drawable files.
