### ISSUE TITLE
Public method : getText is missing

### ISSUE THREAD

**Issue by makuchaku** [medyo/fancybuttons#27]
A missing getText method makes this unusable in onClick events. One has to resort to knowing the internals of FancyButton layout to extract text.

The following complex query is used currently to find text of the button which was clicked

                public void onClick(View view) {
                    TextView tv = (TextView)((LinearLayout) view).getChildAt(0);
                    Log.d("onClick", tv.getText().toString());
                }

Needed
public String getText();

**Comment by medyo** [comment]
Here you go, i just added some basic getters https://github.com/medyo/fancybuttons/commit/0dcabb3a0ef21dd926e2604cfae4fb4dd4bf46c5
