### ISSUE TITLE
text and icon centered in a match_parent(100%) width button?

### ISSUE THREAD

**Issue by rodrigoAbril** [medyo/fancybuttons#28]
Is there any way to have a match_parent(100%) width button with the text and icon centered?

need something like this 
http://ryanharter.com/images/posts/centered-button.png

**Comment by medyo** [comment]
I think you're looking for the same feature here : https://github.com/medyo/fancybuttons/pull/26
it's already fixed, try the version 1.4

**Comment by rodrigoAbril** [comment]
Yes you are correct. Great library.

Thank you.
