### ISSUE TITLE
[solved] Spannable Text

### ISSUE THREAD

**Issue by riinav** [medyo/fancybuttons#29]
Hi, How can we use Spannable Text for the button title?

The setText() method requires String, so cant use spanned text
any other work around?

Html.fromHtml("...");

I am trying this in API level 21 and 22

**Comment by medyo** [comment]
Hi @riinav,
Please try to use the getter `myFancyButton.getTextViewObject()`, so you can manipulate the Text View object according to your needs.

Thanks

**Comment by riinav** [comment]
Awesome that works like a charm...
Thanks for the awesome lib and saving tons of lines of code.

btw, you might consider adding this feature in your wiki

**Comment by medyo** [comment]
it's already added in the section `Supported Getters`
