### ISSUE TITLE
Add to Maven Central

### ISSUE THREAD

**Issue by gautamk** [medyo/fancybuttons#3]
Can we get this added to maven central ?

**Comment by gunhansancar** [comment]
+1

**Comment by zoltanf** [comment]
One more comment for maven central, it makes a great lib really hard to setup/use when you need to include it in the project itself. Thanks for the great work!

**Comment by medyo** [comment]
Sorry guys for the delay.
The project is now synced to Maven central. Just use : 

	compile 'com.github.medyo:fancybuttons:1.0@aar'

Happy Coding

**Comment by daimajia** [comment]
Awesome！

**Comment by Souf-R** [comment]
Great! :+1:
