### ISSUE TITLE
Image Icon not set dynamically

### ISSUE THREAD

**Issue by raonasir** [medyo/fancybuttons#35]
Hi medyo,

How can i set dynamically downloaded images as setIconResource function?
i am confused about it that it is only taking int and string rather than drawable or bitmap.

**Comment by medyo** [comment]
Hi @raonasir ,

There is a method called `setIconResource() ` which accepts Drawable as parameter.
Check this example: https://github.com/medyo/fancybuttons/blob/master/samples/src/main/java/mehdi/sakout/fancybuttons/samples/ProgramButtons.java#L52

**Comment by raonasir** [comment]
Hi @medyo ,

it is when we assign drawable from app folder. when i want to use downloaded images then how can i use those images as setIconResource() ?

**Comment by medyo** [comment]
sorry but your issue isn't related to this library.
However, i'd recommend you to check this answer : http://stackoverflow.com/a/6407554/1725748
If you're using a custom image loader library please check their documentation.

Have a good coding day
