### ISSUE TITLE
fancy:fb_text

### ISSUE THREAD

**Issue by LinkOut** [medyo/Fancybuttons#39]
Hellow, nice lin

Is there a way to set fancy:fb_text bold?

**Comment by medyo** [comment]
Hi @LinkOut,
the current version doesn't support textStyle `bold`, `italic` ...
However, you can easily set it programmatically by doing : 
```
FancyButton myButton = (FancyButton)findViewById(R.id.my_button);
myButton.getTextViewObject().setTypeface(null, Typeface.BOLD);
```

**Comment by LinkOut** [comment]
Awesome, thanks a lot!
