### ISSUE TITLE
invalidate / refreshDrawableState

### ISSUE THREAD

**Issue by vds2014** [medyo/Fancybuttons#43]
How can I set for a custom text font.... i've tryed   assets/font/font_name.ext but nothing hows

**Comment by medyo** [comment]
Hi @vds2014,

Could you share you code so i can figure out the issue ?

Thanks

**Comment by medyo** [comment]
hi @vds2014 

any updates on this ?

**Comment by medyo** [comment]
Please reopen it your problem persists.
