### ISSUE TITLE
Button not showing up

### ISSUE THREAD

**Issue by tachang** [medyo/Fancybuttons#45]
I have a simple button defined like this:
```
        <mehdi.sakout.fancybuttons.FancyButton
            android:id="@+id/rate_button2"
            android:layout_width="100dp"
            android:layout_height="100dp"
            fancy:fb_borderWidth="1dp"
            fancy:fb_defaultColor="#ffffff"
            fancy:fb_focusColor="#9bd823"
            fancy:fb_iconResource="@drawable/rate_button"
            fancy:fb_iconPosition="left"
            fancy:fb_radius="50dp"
            fancy:fb_text="Rate"
            fancy:fb_textColor="#FFFFFF" />

```
But it is showing up like this?

<img width="101" alt="screen shot 2016-01-31 at 7 58 28 am" src="https://cloud.githubusercontent.com/assets/85011/12703146/956a3f94-c7f0-11e5-9666-1ded88295a5e.png">

**Comment by medyo** [comment]
Hi @tachang,

Please, Make sure you added `xmlns:fancy="http://schemas.android.com/apk/res-auto"` as described on the documentation.

Thanks

**Comment by medyo** [comment]
@tachang  Any updates on this ?

**Comment by medyo** [comment]
If the issue still persists, please reopen
