### ISSUE TITLE
text worng show 

### ISSUE THREAD

**Issue by zhew117** [medyo/Fancybuttons#47]
<mehdi.sakout.fancybuttons.FancyButton
        android:id="@+id/item_buy"
        android:layout_width="200dip"
        android:layout_height="38dip"
        fancy:fb_defaultColor="#ff9900"
        fancy:fb_focusColor="#dd8603"
        fancy:fb_radius="4dp"
        fancy:fb_text="SHOW_WRONG"
        />

just show the half top of the content on SAMSUNG GT-I9200

**Comment by zhew117** [comment]
![c q h ur_ t 2 b66 g 2](https://cloud.githubusercontent.com/assets/3273342/13695976/43aea136-e79e-11e5-8386-66211e634b14.jpg)

**Comment by medyo** [comment]
Hi @zhew117,

Try to use `android:layout_height="wrap_content"` with some padding on Top and Bottom according to your needs

**Comment by medyo** [comment]
@zhew117 any updates on this ?

**Comment by medyo** [comment]
Please reopen it your problem persists.

**Comment by zhew117** [comment]
@medyo I should have closed this one  :) thansk a lot

**Comment by hzw1199** [comment]
`android:layout_height="wrap_content"` solve this problem, but there is still so much padding on Top and Bottom of the text, which looks not so comfortable @medyo
