### ISSUE TITLE
How do I create circle buttons?

### ISSUE THREAD

**Issue by jessejohnson** [medyo/fancybuttons#5]
Hi,
You've got a really awesome library. Thanks for making Android buttons saner :dancer: 
But, I can't figure out how to make circular fancybuttons.
I'm setting ```fancy:radius="30dp"``` but it feels hacky, and doesn't always yield perfectly round buttons.

I see some circle buttons in your documentation images. Is there something I'm missing?

**Comment by medyo** [comment]
Well there is no special method for that right now, but as you said you can use the radius with value equals to the half of button size. like 30dp for a button of 60dp HeightxWidth. So you can create a perfect circle effect.

**Comment by jessejohnson** [comment]
Okay. I hope there'll be a feature like that sometime in the future. Thanks :)
