### ISSUE TITLE
FancyButton text does not appear in Dialog

### ISSUE THREAD

**Issue by Geoffrey63** [medyo/Fancybuttons#52]
If I try to display a FancyButton in a Dialog, I get the following result : 

<img width="201" alt="capture d ecran 2016-03-30 a 18 04 03" src="https://cloud.githubusercontent.com/assets/1381553/14148994/50c3fb42-f6a2-11e5-94dd-2c0f1c1eb9e6.png">

I used the exact same code as the sample (Spotify button).

Do you have a clue about that ?

**Comment by medyo** [comment]
Did you applied a custom style to your Dialog ?
If so try to disable `background attribute`

**Comment by Geoffrey63** [comment]
Good point, I disabled the background in the style and it works fine.

Thanks for your help.

**Comment by nikitoSha** [comment]
I have the same issue, but I don't use background in style. What's wrong?
