### ISSUE TITLE
Set Drawable as Icon

### ISSUE THREAD

**Issue by carmas123** [medyo/Fancybuttons#55]
How can I set manually the drawable icon?

public void setIconResource(int drawable)
public void setIconResource(String icon)
 public void setIconResource(Drawable drawable) <--- ??? Missing :)

**Comment by medyo** [comment]
Hi @carmas123,

Actually, there is no direct setter for Drawable object, could you make a Pull request for such edit ?

**Comment by medyo** [comment]
`setIconResource(Drawable)` is now available, Try the new version `1.8`
