### ISSUE TITLE
Can't set focus to a button

### ISSUE THREAD

**Issue by peppe130** [medyo/Fancybuttons#56]
Hi,
I want to set the borderColor when the button is focused but it does nothing. Nothing change. It's like your library doesn't support focus listener. Could you help me? Thanks

**Comment by medyo** [comment]
Hi @peppe130,

`Fancybuttons` doesn't implement any custom callback internally. 
For your case I think you should enable the focus feature by calling : 
~~~java
myButton.setFocusable(true);
myButton.setFocusableInTouchMode(true);
~~~

**Comment by peppe130** [comment]
I solved using `setOnTouchListener` method.

`myButton.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                    switch (motionEvent.getAction()) {
                        case MotionEvent.ACTION_DOWN:
                            myButton.setBorderColor(getResources().getColor(R.color.colorButtonBorder));
                            return false;
                        case MotionEvent.ACTION_UP:
                            myButton.setBorderColor(0);
                            return false;
                        case MotionEvent.ACTION_CANCEL:
                            myButton.setBorderColor(0);
                            return false;
                    }
                return false;
            }
        });`

**Comment by medyo** [comment]
Okay, I thought you were talking about `Focus Listener`, Sorry
your listener `setOnTouchListener` should work perfectly.

**Comment by peppe130** [comment]
It's OK! Keep up the good work!
