### ISSUE TITLE
Icon drawabe is not centered by default?

### ISSUE THREAD

**Issue by tsunamilx** [medyo/Fancybuttons#58]
Hi 

I found the icon drawable is not centered, even if I used gravity attribute, see screenshot (the arrow down icon on the top right):
![image](https://cloud.githubusercontent.com/assets/6290337/15064261/eb5596bc-1384-11e6-936a-4b00388a9cb1.png)

I have to use icon padding to do so. Am I using something wrong or this can be improved.

**Comment by carmas123** [comment]
You can solve it with a simple trick :)
This is Kotlin language but simple translate it in Java:

myButton.iconImageObject.lparams { gravity = Gravity.CENTER_VERTICAL }

Anyway you have iconImageObject property of FancyButton class that help you.
If you use kotlin this is very simple making an extension of FancyButton class
Bye

**Comment by medyo** [comment]
@tsunamilx could you share with us your code

**Comment by tsunamilx** [comment]
Actually I solved by adding one line to your code:
```java
    private ImageView setupIconView() {
        if (mIconResource != null) {
            ImageView iconView = new ImageView(mContext);
            iconView.setImageDrawable(mIconResource);
            iconView.setPadding(mIconPaddingLeft, mIconPaddingTop,
                                mIconPaddingRight, mIconPaddingBottom);

            LayoutParams iconViewParams = new LayoutParams(
                LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
            if (mTextView != null) {
                if (mIconPosition == POSITION_TOP
                    || mIconPosition == POSITION_BOTTOM) {
                    iconViewParams.gravity = Gravity.CENTER;
                } else {
                    // Added line here
                    iconViewParams.gravity = Gravity.CENTER_VERTICAL;
                }

                iconViewParams.rightMargin = 10;
                iconViewParams.leftMargin = 10;
            } else {
                iconViewParams.gravity = Gravity.CENTER_VERTICAL;
            }
            iconView.setLayoutParams(iconViewParams);

            return iconView;
        }
        return null;
    }
```

**Comment by monowar1993** [comment]
We need more control over icon. As I would like to set the icon on the left side of the button. Is there any way??

**Comment by medyo** [comment]
to set the icon to the left just use `fancy:fb_iconPosition="left"`
If you need more control, there is a getter of the icon object `getIconFontObject()` or `getIconImageObject ()`

**Comment by amatkivskiy** [comment]
+ 1 to this issue. Can `iconViewParams.gravity = Gravity.CENTER_VERTICAL` be added to the library? I think it is a quite common requirement when configuring icon for the FancyButton. @medyo  What do you think?

**Comment by jarro** [comment]
Just updated to latest version from 1.7 and icons are no longer centered vertically.    Will try to resolve with top and bottom padding.

**Comment by adityahas** [comment]
This issue happen if the icon is vector, it's fine if it image.

**Comment by adityahas** [comment]
I think I found the fix by changing the icon view gravity to CENTER_VERTICAL instead of START (FancyButton.java:270). @medyo Can you please check it?
