### ISSUE TITLE
How to get text on the button 

### ISSUE THREAD

**Issue by laylizzlle** [medyo/fancybuttons#6]
Everything works perfectly but getText()  gives an error is there a way around it

**Comment by squeeish** [comment]
Hi @laylizzlle, how did you solve it?

**Comment by laylizzlle** [comment]
I saved the String in a variable anytime i used setText() on the button and just used that variable anytime a wanted to get the text.U get it? @squeeish

**Comment by squeeish** [comment]
@laylizzlle thanks, I solved it by setTag and getTag methods instead.

**Comment by medyo** [comment]
Well actually, we don't serve getter functions. Maybe in coming versions
