### ISSUE TITLE
The button doesn't render automatically in xml preview editor

### ISSUE THREAD

**Issue by jaychang0917** [medyo/Fancybuttons#60]
Each time i made some changes of xml, the button will not be rendered automatically, and I  need to manually refresh the layout preview.

**Comment by medyo** [comment]
`Fancybuttons` does support real time rendering, please check your configuration

**Comment by jaychang0917** [comment]
I figured out it, it is working now. Thanks

**Comment by or-dvir** [comment]
@jaychang0917 please post your solution so other people with the same question (like me) could also fix it
