### ISSUE TITLE
Icon not displaying in button, showing file path in directory instead

### ISSUE THREAD

**Issue by pcodemang** [medyo/Fancybuttons#62]
Just started using, so highly probable it is my own mistake. It is also not displaying the icon correctly in the preview. It shows me a circle near the text. It is supposed to look like https://cdn0.iconfinder.com/data/icons/thin-voting-awards/24/thin-0665_vote_ticket_paper_voting-128.png
```
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                xmlns:fancy="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingBottom="@dimen/activity_vertical_margin"
                android:paddingLeft="@dimen/activity_horizontal_margin"
                android:paddingRight="@dimen/activity_horizontal_margin"
                android:paddingTop="@dimen/activity_vertical_margin"
                tools:context=".activites.VoteActivity">
```

    <android.support.v7.widget.RecyclerView
        android:id="@+id/classification_select"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_marginTop="39dp"
        android:layout_below="@+id/textView"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="?android:attr/textAppearanceMedium"
        android:text="Question"
        android:id="@+id/textView"
        android:layout_alignParentTop="true"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="27dp"/>

    <mehdi.sakout.fancybuttons.FancyButton
        android:id="@+id/btn_vote"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/classification_select"
        android:paddingRight="10dp"
        fancy:fb_borderWidth="1dp"
        fancy:fb_fontIconResource="@drawable/ic_votee"
        fancy:fb_fontIconSize="30sp"
        android:layout_centerHorizontal="true"
        fancy:fb_radius="10dp"
        fancy:fb_text="SUBMIT"
        fancy:fb_iconPosition="left"
        fancy:fb_defaultColor="#4a148c"
        />

</RelativeLayout>
![erro](https://cloud.githubusercontent.com/assets/17652993/15459381/a6da5310-2072-11e6-8e20-708f71d56835.png)
`

**Comment by medyo** [comment]
Hi @pcodemang, please read the documentation carefully or check samples, 

to set a font icon use `fancy:fb_fontIconResource="myIconFont"`
to set a drawable icon, **which is your case**, use `fancy:fb_iconResource="MyDrawableIcon"`

**Comment by pcodemang** [comment]
Oh, my mistake. Thank you for the help
