### ISSUE TITLE
FontIconColor can not be set differently!

### ISSUE THREAD

**Issue by ahmetcj4** [medyo/Fancybuttons#63]
Although fontIcon size can be set independent of the text size, I couldn't manage change the color of the fontIcon

**Comment by medyo** [comment]
Hi @ahmetcj4,

you could change icon size by calling `fancy:fb_fontIconSize` or `setFontIconSize(int)`

**Comment by ahmetcj4** [comment]
Is it possible to set different colors for FontIcon and IconText?

**Comment by medyo** [comment]
@ahmetcj4 please check `supported-attributs` to know library abilities https://github.com/medyo/Fancybuttons#supported-attributs

The current version doesn't support different colors for text and icon, however you achieve that by using these getters https://github.com/medyo/Fancybuttons#supported-getters

**Comment by ahmetcj4** [comment]
now I can change colors, thank you !

**Comment by ajithkpistar** [comment]
fancy_button.getIconFontObject().setTextColor(getResources().getColor(R.color.colorAccent));
