### ISSUE TITLE
Could not find class 'android.graphics.drawable.RippleDrawable'

### ISSUE THREAD

**Issue by meeftah** [medyo/Fancybuttons#64]
I got an error:
`Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method mehdi.sakout.fancybuttons.FancyButton.getRippleDrawable`

even though my app running perfectly...

**Comment by medyo** [comment]
hi @meeftah,

what API Version do you use ?

**Comment by meeftah** [comment]
1.8.1

**Comment by medyo** [comment]
Hi @meeftah,

Sorry but I'm talking about the Android API Version

**Comment by medyo** [comment]
RippleDrawable was introduced in API 21, so make sure your project runs in this version or +
