### ISSUE TITLE
Vector drawable cannot be used in the button

### ISSUE THREAD

**Issue by suku-h** [medyo/Fancybuttons#68]
I tried using a vector drawable as an iconResource. While the vector drawable is rendering, it is not picking up the condition for position and the text is not being displayed. 

`<mehdi.sakout.fancybuttons.FancyButton
            android:id="@+id/fworkouttype_fb_musclegain"
            android:layout_width="@dimen/d_250"
            android:layout_height="@dimen/d_80"
            android:textAllCaps="false"
            android:textStyle="bold"
            fancy:fb_text="@string/musclegain"
            fancy:fb_textSize="@dimen/s_24"
            fancy:fb_textColor="@color/white"
            fancy:fb_textGravity="center"
            fancy:fb_iconResource="@drawable/vector_musclegain"
            fancy:fb_iconPosition="left"
            fancy:paddingStart="@dimen/d_10"
            fancy:paddingEnd="@dimen/d_10"
            fancy:fb_iconPaddingTop="@dimen/d_10"
            fancy:fb_iconPaddingBottom="@dimen/d_10"
            fancy:fb_defaultColor="@color/positive"
            fancy:fb_focusColor="@color/positiveClicked"
            fancy:fb_radius="@dimen/d_40"/>`

The output of using the vector drawable
![fb_vector](https://cloud.githubusercontent.com/assets/17564687/17728500/28d4ace6-647d-11e6-8bca-e79320cff1bc.PNG)

This is the same code using a png:
`<mehdi.sakout.fancybuttons.FancyButton
            android:id="@+id/fworkouttype_fb_weightloss"
            android:layout_width="@dimen/d_250"
            android:layout_height="@dimen/d_80"
            android:textAllCaps="false"
            android:textStyle="bold"
            fancy:fb_text="@string/weightloss"
            fancy:fb_textSize="@dimen/s_24"
            fancy:fb_textColor="@color/white"
            fancy:fb_iconResource="@drawable/play"
            fancy:fb_iconPosition="left"
            fancy:paddingStart="@dimen/d_10"
            fancy:paddingEnd="@dimen/d_10"
            fancy:fb_iconPaddingTop="@dimen/d_10"
            fancy:fb_iconPaddingBottom="@dimen/d_10"
            fancy:fb_defaultColor="@color/positive"
            fancy:fb_focusColor="@color/positiveClicked"
            fancy:fb_radius="@dimen/d_40"/>`

output of using png:
![fb_png](https://cloud.githubusercontent.com/assets/17564687/17728540/51dc0abc-647d-11e6-8e1c-527e2d2a6633.PNG)

It would be great if your library could support vector drawables. I am planning to make all my png icons into vector drawables.

**Comment by medyo** [comment]
Hi @suku-h, that's really weird, I just tried on my own and it works like a charm !

here is my example :

```
<mehdi.sakout.fancybuttons.FancyButton
android:id="@+id/btn_instagram"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_marginBottom="10dp"
android:padding="10dp"
fancy:fb_borderColor="#FFFFFF"
fancy:fb_borderWidth="2dp"
fancy:fb_defaultColor="#40a75a"
fancy:fb_focusColor="#8cc9f8"
fancy:fb_textGravity="center"
fancy:fb_iconResource="@drawable/icon_instagram"
fancy:fb_fontIconSize="30sp"
fancy:fb_iconPosition="left"
fancy:fb_text="Instagram"
fancy:fb_radius="10dp"
fancy:fb_textColor="#FFFFFF"/>    
```

**Comment by suku-h** [comment]
I tried your code but this is the output I get when I used vector drawable:

![medyoreply](https://cloud.githubusercontent.com/assets/17564687/17840898/24a8f9fa-682f-11e6-864e-fe83c8f2a6e1.PNG)

You can get the vector drawable [here](http://s000.tinyupload.com/?file_id=44684698912514916685) that I used. 

Does it have to do with different phones? Or Marshmellow?

**Comment by suku-h** [comment]
I went through your code. The problem is caused because your are inflating the imageview with WRAP_CONTENT layouts. The WRAP_CONTENT size for this image is 591px, hence the imageview is inflating to that size but the fancybutton is limited by the size of the dimensions assigned.
