### ISSUE TITLE
If it can set the TextStyle，it would be better.

### ISSUE THREAD

**Issue by Wade-Cai** [medyo/Fancybuttons#69]
Thanks for medyo's project

**Comment by medyo** [comment]
Hi @Wade-Cai,

yes, it's possible by using the getter `getTextViewObject ()`, you could apply whatever styles you like

does it answer your question?

**Comment by odetoyama** [comment]
Hi @medyo thanks for the clue.

I can get the textView object, set the style into it and etc. but I can't set the textView back to the FancyButton.

**Comment by roman-ku** [comment]
+1 Would love this as well, would like an XML attribute to do it

**Comment by roman-ku** [comment]
#112
