### ISSUE TITLE
Text is centered 

### ISSUE THREAD

**Issue by simoelmou** [medyo/fancybuttons#8]
" textView.setGravity(Gravity.CENTER); " 
Make the text centered which i don't prefer and in 2 lines, i wish if there is a way to get around it ?
![untitled](https://cloud.githubusercontent.com/assets/5102537/6423532/d2e1901a-bee7-11e4-881d-ce324f455582.png)

**Comment by medyo** [comment]
Well it's not yet implemented, but if your project depends heavily on it, feel free to make that feature for the community !
