### ISSUE TITLE
Add capability to make radius on selected position (ex : bottomLeftRadius and bottomRightRadius)

### ISSUE THREAD

**Issue by wafda** [medyo/Fancybuttons#85]
Could you please add capability to put radius in specific position?
<img width="382" alt="screen shot 2017-05-22 at 3 47 22 pm" src="https://cloud.githubusercontent.com/assets/14181683/26299698/f72fd7e2-3f05-11e7-8ff3-7fd6ea1dc8b8.png">

<img width="308" alt="screen shot 2017-05-22 at 3 46 42 pm" src="https://cloud.githubusercontent.com/assets/14181683/26299688/ebab1cec-3f05-11e7-9ad1-38f3ae28bcaf.png">

**Comment by medyo** [comment]
Hi @wafda,

This option isn't available, if you project depends heavily on it, feel free to make a new pull request.
Here is the way to do it: https://developer.android.com/reference/android/graphics/drawable/GradientDrawable.html#setCornerRadii(float[])

Thank you
