### ISSUE TITLE
Remove icon

### ISSUE THREAD

**Issue by ZlotIv** [medyo/Fancybuttons#86]
Hello. How can I remove Icon programmatically?

**Comment by medyo** [comment]
Hi @ZlotIv,
This option isn't available in the current version, however you can remove it like any other view by calling `myButton. removeView(myButton.getIconImageObject()) `

**Comment by ZlotIv** [comment]
thank you.

**Comment by medyo** [comment]
if everything is Okay, don't forget to close the issue.
Have a nice coding day
