### ISSUE TITLE
Circular button?

### ISSUE THREAD

**Issue by bkawakami** [medyo/fancybuttons#9]
hey guys

I tried make a circular button. In my Moto G is perfect, but in Galaxy S5 of my friend the button not is circular :/

How I can make a real circular button?

```xml
<mehdi.sakout.fancybuttons.FancyButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="10dp"
            android:paddingTop="15dp"
            android:paddingBottom="15dp"
            android:paddingLeft="17dp"
            android:paddingRight="17dp"
            fancy:radius="30dp"
            fancy:fontIconSize="11dp"
            fancy:fontIconResource="&#xf067;"
            fancy:defaultColor="@color/buttons"
            fancy:focusColor="@color/buttonsFocus"
            android:id="@+id/buttonMore" />
```

**Comment by bkawakami** [comment]
any way, my Android is Lollipop and Android of my friend is KitKat

**Comment by medyo** [comment]
Unfortunately, there is no direct method to draw a perfect circle right now, however if your project depends heavily on it, feel free to make that feature for the community ! It's not hard to implement

**Comment by bkawakami** [comment]
you have reason, if we need some thing we can build it. I don't have much experience in Android but I will try

**Comment by bkawakami** [comment]
Thanks @medyo

**Comment by azizimusa** [comment]
its fancy:fb_radius not fancy:radius
