### ISSUE TITLE
"Fancy Button" text by default

### ISSUE THREAD

**Issue by emrealparslan93** [medyo/Fancybuttons#98]
Hello,

I updated FancyButtons version to 1.8.4 from 1.5 and my fancy buttons which do not contain **fancy:fb_text** attribute, starts to display "Fancy Button" text by default.

Here is what happened when I started to use 1.8.4 : 
![screen shot 2017-09-20 at 16 26 24](https://user-images.githubusercontent.com/9310800/30646110-87fe6580-9e20-11e7-9f06-d78024a91d93.png)

If I add **fancy:fb_text=""** attribute to the button, text goes away of course.

Is it something intentionally added ?

**Comment by MahdiPishguy** [comment]
@emrealparslan93 by default when you want to have empty text you have to add `fancy:fb_text=""` into xml

**Comment by emrealparslan93** [comment]
@MahdiPishguy Yes I did that. I just wondered if there is a bug about it because I thought it shouldn't be like that. Thank you for your response.
